POST http://localhost:3000/api/ HTTP/1.1
Content-Type: application/json

{
    "title": "Crear una pagina API",
    "content": "Tengo que crear una API y conectarla al frontend"
}

###

GET http://localhost:3000/api/ HTTP/1.1

###

GET http://localhost:3000/api/605a8af7d6264d00dc420d97 HTTP/1.1

###

PUT http://localhost:3000/api/605a06693594d61f984e2c5f HTTP/1.1
Content-Type: application/json

{
    "title": "Crear una pagina web",
    "content": "Tengo que crear una pagina web para una tienda"
}

###

DELETE http://localhost:3000/api/605a06693594d61f984e2c5f HTTP/1.1